<p>
<label for="AdSenseAnna-Title">Title: </label><br>
<input type="text" id="AdSenseAnna-Title" name="AdSenseAnna-Title" value="<?php echo $options['AdSenseAnna-Title'];?>" />    
</p>

<p>
<label for="AdSenseAnna-AdSenseID">AdSense-ID: </label><br>
<input type="text" id="AdSenseAnna-AdSenseID" name="AdSenseAnna-AdSenseID" value="<?php echo $options['AdSenseAnna-AdSenseID'];?>" />    
</p>

<p>
<label for="AdSenseAnna-WidgetBanner">Banner: </label><br>
<select name="banner" size="1">
	<optgroup label="Adsense Image">
		<optgroup label="Banner Vertikal">
			<option value="adsense_banner_vertical_120x600">120 x 600 Skyscraper</option>
			<option value="adsense_banner_vertical_160x600">160 x 600 Wide Skyscraper</option>
		</optgroup>
		<optgroup label="Banner Square">
			<option value="adsense_banner_square_336x280">336 x 280 Large Rectangle</option>
			<option value="adsense_banner_square_300x250">300 x 250 Medium Rectangle</option>
			<option value="adsense_banner_square_250x250">250 x 250 Square</option>
			<option value="adsense_banner_square_200x200">200 x 200 Small Square</option>		
		</optgroup>
	</optgroup>
	<optgroup label="Adsense Text">
		<optgroup label="Text Vertikal">
			<option value="adsense_text_vertical_120x600">120 x 600 Skyscraper</option>
			<option value="adsense_text_vertical_160x600">160 x 600 Wide Skyscraper</option>
			<option value="adsense_text_vertical_120x240">120 x 240 Vertical Banner</option>
		</optgroup>
		<optgroup label="Text Square">
			<option value="adsense_text_square_336x280">336 x 280 Large Rectangle</option>
			<option value="adsense_text_square_300x250">300 x 250 Medium Rectangle</option>
			<option value="adsense_text_square_250x250">250 x 250 Square</option>
			<option value="adsense_text_square_200x200">200 x 200 Small Square</option>		
			<option value="adsense_text_square_180x150">180 x 150 Small Rectangle</option>
			<option value="adsense_text_square_125x125">125 x 125 Button</option>				
		</optgroup>
	</optgroup>	
</select>
</p>
<p><a href="http://kopy-online.de" target="_blank">need help?</a></p>

<input type="hidden" id="AdSenseAnna-submit" name="AdSenseAnna-submit" value="1" />
